# Generated by Django 4.0.6 on 2022-08-10 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_familiar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
